# Dockerfile for JupyterLab
# Jupyterhub version: 3.1.1

FROM jupyter/datascience-notebook:hub-3.1.1

# JupyterHub Version
ARG JUPYTERHUB_VERSION=3.1.1

# Install packages
RUN pip3 install --no-cache \
    jupyterlab-language-pack-pl-PL